const list = document.querySelector('.list')
const button = document.querySelector('svg')
const header = document.querySelector('.header-element')
const headerMain = document.querySelector('header')
const navbar = document.querySelector('.hello')
const wrapper = document.querySelector('.nav-list-wrapper')
const nav = document.querySelector('nav')
const part1 = document.querySelector('.part-1')
const part2 = document.querySelectorAll('.part-2')
const part3 = document.querySelector('.part-3')
const part4 = document.querySelector('.part-4')
const part5 = document.querySelector('.part-5')
const part6 = document.querySelector('.part-6')
const part7 = document.querySelector('.part-7')
const part8 = document.querySelector('.part-8')
const part9 = document.querySelector('.part-9')
const footer = document.querySelector('footer')
const links = document.querySelectorAll('.test')
const svg = document.querySelector('svg')


button.addEventListener('click', () => {
    part1.classList.contains('none') ? part1.classList.remove('none') : part1.classList.add('none')
    header.classList.contains('none') ? header.classList.remove('none') : header.classList.add('none')
    headerMain.classList.contains('no-bg-img') ? headerMain.classList.remove('no-bg-img') : headerMain.classList.add('no-bg-img')
    for (let i of part2) {
        i.classList.contains('none') ? i.classList.remove('none') : i.classList.add('none')
    }
    part3.classList.contains('none') ? part3.classList.remove('none') : part3.classList.add('none')
    part5.classList.contains('none') ? part5.classList.remove('none') : part5.classList.add('none')
    part6.classList.contains('none') ? part6.classList.remove('none') : part6.classList.add('none')
    part7.classList.contains('none') ? part7.classList.remove('none') : part7.classList.add('none')
    part8.classList.contains('none') ? part8.classList.remove('none') : part8.classList.add('none')
    part9.classList.contains('none') ? part9.classList.remove('none') : part9.classList.add('none')
    svg.classList.contains('up') ? svg.classList.remove('up') : svg.classList.add('up')
    footer.classList.contains('none') ? footer.classList.remove('none') : footer.classList.add('none')
    navbar.classList.contains('collapse') ? navbar.classList.remove('collapse') : navbar.classList.add('collapse')
    wrapper.classList.contains('collapse') ? wrapper.classList.remove('collapse') : wrapper.classList.add('collapse')
    nav.classList.contains('nav-collapse') ? nav.classList.remove('nav-collapse') : nav.classList.add('nav-collapse')
    for (let j of links) {
        j.classList.contains('black') ? j.classList.remove('black') : j.classList.add('black')
    }
})
console.dir(part1.classList.contains('sdqw'))
console.log('test')